name: Build package reusable task

on:
    # Testing reusable workflows
    workflow_call:
        # Inputs the workflow accepts.
        inputs:
            branch:
                required: true
                type: string
            use-slack:
                description: 'Should there be a slack notification'
                type: boolean
                default: false
            package-name:
                description: 'A package name to be used in the slack notification'
                type: string
                required: false

        secrets:
            git-token:
                description: 'A git token passed from the caller workflow'
                required: true
            npm-token:
                description: 'A npm token passed from the caller workflow'
                required: true
            slack-webhookurl:
                description: 'A slack webhook url for status notification'
                required: false

jobs:
    npm-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '14.x'
                  registry-url: 'https://registry.npmjs.org'
                  token: ${{ secrets.git-token }}
            - name: Checkout to the branch
              run: |
                  git fetch
                  git reset --hard HEAD
                  git checkout ${{ inputs.branch }}
            - name: Identify
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
            - name: Install
              run:
                  npm install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
            - name: Build
              id: runBuild
              run:
                  npm run build
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
            - name: Post success to Slack
              if: ${{ success() && inputs.use-slack }}
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  payload: |
                      {
                          "package-name": "${{ inputs.package-name }}",
                          "branch": "${{ inputs.branch }}",
                          "build_status": "success"
                      }
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.slack-webhookurl }}
            - name: Post failure to Slack
              if: ${{ failure() && inputs.use-slack }}
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  payload: |
                      {
                          "package-name": "${{ inputs.package-name }}",
                          "branch": "${{ inputs.branch }}",
                          "build_status": "failed"
                      }
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.slack-webhookurl }}
