name: Check for Alpha Techsee Packages

on:
  workflow_call:
    inputs:
      package-path:
        description: 'Path to the package.json file'
        required: false
        default: './package.json'
        type: string

jobs:
  check-alpha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate package.json and check for alpha techsee packages
        shell: bash
        run: |
          PACKAGE_JSON_PATH="${{ inputs.package-path }}"
          
          # Validate package.json
          if ! grep -q '{' "$PACKAGE_JSON_PATH"; then
            echo "Invalid package.json format."
            exit 1
          fi

          # Extract lines containing @techsee/ and -alpha
          alpha_packages=$(grep '@techsee/.*-alpha' "$PACKAGE_JSON_PATH" || true)

          if [ -n "$alpha_packages" ]; then
            echo "Alpha version of a techsee package found:"
            echo "$alpha_packages"
            exit 1
          else
            echo "No alpha techsee packages found."
          fi
