name: Test reusable task

on: 
  # Testing reusable workflows
  workflow_call:
      # Inputs the workflow accepts.
      inputs:
        baseBranch:
          default: dev
          type: string
        releaseVersion:
          required: true
          type: string
          
      secrets:
        GITHUB_TOKEN:
          required: true
jobs:
  create-release-and-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release branch
        run: |
          git fetch
          git checkout ${{ github.event.inputs.baseBranch }}
          git checkout -b v${{ github.event.inputs.releaseVersion }}
      - name: Commit the changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Bump to v${{ github.event.inputs.releaseVersion }}"
      - name: Push the new release branch
        run:
          git push origin v${{ github.event.inputs.releaseVersion }}
      
